In [1]:
import pandas as pd
import numpy as np
from calculator import *

In [5]:
data = pd.read_csv("arsenic.csv")

In [6]:
data.head()

,StateWellNumber,County,AquiferCode,WellDepth,Date,Time,SampleNumber,EntityId,LabId,ReliabilityId,CollectionRemarks,LatitudeDD,LongitudeDD,ParameterCode,ParameterDescription,ParameterFlag,ParameterValue,ParameterUnit,PlusMinus
0,3458904,Anderson,124WLCX,1032.0,4/27/1993,1415.0,1.0,1.0,1.0,7.0,Analysis Balanced.,32.016103,-95.751856,1000.0,"ARSENIC, DISSOLVED (UG/L AS AS)",<,1.0,ug/L,NaN
1,3458904,Anderson,124WLCX,1032.0,5/20/1998,1212.0,1.0,1.0,23.0,7.0,Analysis Balanced.,32.016103,-95.751856,1000.0,"ARSENIC, DISSOLVED (UG/L AS AS)",<,2.0,ug/L,NaN
2,3458904,Anderson,124WLCX,1032.0,3/12/2002,1530.0,1.0,1.0,23.0,7.0,Analysis Balanced.,32.016103,-95.751856,1000.0,"ARSENIC, DISSOLVED (UG/L AS AS)",<,2.0,ug/L,NaN
3,3458904,Anderson,124WLCX,1032.0,10/26/2005,1130.0,1.0,1.0,24.0,7.0,Analysis Balanced. Petcock on discharge in bldg,32.016103,-95.751856,1000.0,"ARSENIC, DISSOLVED (UG/L AS AS)",<,1.0,ug/L,NaN
4,3458904,Anderson,124WLCX,1032.0,4/23/2010,1005.0,1.0,1.0,23.0,7.0,Analysis Balanced. Lab Calculated Anion/Catio...,32.016103,-95.751856,1000.0,"ARSENIC, DISSOLVED (UG/L AS AS)",<,2.0,ug/L,NaN

In [7]:
a = pre_process(data,[0,3,6,100],["zero","moderate",'high'])
a

TypeError: unhashable type: 'DataFrame'

In [134]:
a.shape

(2545, 4)